### ISSUE TITLE
Provide `Coradoc::Document.to_adoc` method to output to AsciiDoc string

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/coradoc#10]

**Comment by abunashir** [comment]
Haven't look into it for ages, but if I remember correctly we do have that option now but it's not feature complete.

**Comment by ronaldtse** [comment]
@hmdne for some reason this task is conspicuously missing even when we have `to_adoc` methods for all nodes?

**Comment by hmdne** [comment]
It is fixed now, yes.
