### ISSUE TITLE
(URGENT) Tables not being encoded to Metanorma Asciidoc

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/coradoc#138]
From  https://github.com/metanorma/iso-sa-10-3000/issues/1, tables are being left in XML format:

![Screenshot 2024-10-24 132419](https://github.com/user-attachments/assets/8f4b9f90-5993-460d-b639-aefb48b98d6d)

**Comment by hmdne** [comment]
This has been fixed by #135 already, but there was another small issue introduced later on. I will follow up with a PR and a release.
