### ISSUE TITLE
Specs failing due to "Resource not accessible by integration" in "tests-passed"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/coradoc#60]
@CAMOBAP can you help? Thanks!

https://github.com/metanorma/coradoc/actions/runs/9202817448

**Comment by CAMOBAP** [comment]
The issue isn't related to workflow itself. We have the same issue in the past for isodoc, and some other private repos.
@ronaldtse could you please make sure that METANORMA_CI_PAT_TOKEN has write perissions

**Comment by ronaldtse** [comment]
@camobap in this case it does have write permissions to this repository. What else could be the problem?

**Comment by CAMOBAP** [comment]
IDK why and how but METANORMA_CI_PAT_TOKEN isn't accessible by this repo because https://github.com/metanorma/coradoc/pull/63 fix worked

**Comment by ronaldtse** [comment]
@CAMOBAP very strange. I wonder if we can use this approach for all repositories? Is it easier to manage?

**Comment by CAMOBAP** [comment]
Yep, I will update main configuration in metanorma/ci repo and apply it on next update

@ronaldtse please let me know if you observe the same issue for some other repos
