### ISSUE TITLE
reverse_adoc: Clause levels 4 and 5 for Plateau document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/coradoc#69]
I used this command to test the document:
```sh
bundle exec reverse_adoc -rcoradoc/reverse_adoc/plugins/plateau --split-sections 2 --external-images -o plateau/index.adoc index.html 
```

File:
`plateau/sections/section-04/section-02.adoc`:

```adoc
[[toc4_02_01_02]]
===== (2)　建築物モデル（LOD1）

===== 1)　建築物モデル（LOD1）の概要

建築物モデル（LOD1）では、建築物の形状を立体により表現する。

建築物モデル（LOD1）の取得イメージを表 4-8に示す。
```

As described in #66:
* Clause level 4 `===== (2)　建築物モデル（LOD1）` should be `===== 建築物モデル（LOD1）`

However, `===== 1)　建築物モデル（LOD1）の概要` is clause level 5.

Therefore it should be:
```adoc
// before
===== 1)　建築物モデル（LOD1）の概要

// after
[level=6]
===== 建築物モデル（LOD1）の概要
```

**Comment by hmdne** [comment]
I see some discrepancies here, in AsciiDoc syntax - I use this document as a guide: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

The last markup level of our document is `<h4>` == `=====`.

According to the reference, levels can go up to 5, where the last one, `======` corresponds to `<h5>` (but the reference and AsciiDoctor agree on `<h6>` of this level's representation - let's ignore that for now).

Your suggestion is to output the following code:

```
[level=6]
===== 建築物モデル（LOD1）の概要
```

I think you meant `level=5`. Which could be represented either as:

```
====== 建築物モデル（LOD1）の概要
```

Or as:

```
[level=5]
===== 建築物モデル（LOD1）の概要
```

I am creating a patch for the second case.

**Comment by ronaldtse** [comment]
> I think you meant `level=5`.

Whatever Asciidoctor says would be correct here. Thanks for checking.

In Coradoc, we should remove the need for `level=?` because that was an arbitrary decision by Asciidoctor to limit the number of `=` symbols.
