### ISSUE TITLE
reverse_adoc: Headings: generate titles compatible with AsciiDoctor

### ISSUE THREAD

**Issue by hmdne** [metanorma/coradoc#79]
> @hmdne we want to be compatible with Asciidoctor, so h6 goes to 6 equal signs and vice versa. Thanks.

_Originally posted by @ronaldtse in https://github.com/metanorma/coradoc/issues/76#issuecomment-2141919338_
            
The task is to make it so for example `<h3>` will generate an output of `===` and not `====` as it does currently.

The problem that I see, is that `=` is not a section title. Currently it's generated from a `<title>` tag. A document can only have one `=` tag if it's an `article`.

**Comment by ronaldtse** [comment]
So this is where we have to differ. 

Our conversion target is actually Metanorma. It happens that Metanorma mostly uses Asciidoctor for parsing. 

In Metanorma AsciiDoc,
- One equal sign is the document title
- Two equal signs for the first level clause
- asciidoctor parses until 6 equal signs, which for us is the 5th level clause. 
- asciidoctor does not accept more than 6 equal signs so Metanorma uses a special “levels=“ syntax. 

So when I meant Asciidoctor compatible, I really meant Metanorma compatible.

**Comment by hmdne** [comment]
Note, that this issue is about conversion from HTML, so we are talking about `<h1>` tags, etc.

As of now, `<hX>` tag generates a section with title of level X (`"=" * (X+1)`). This issue is about changing the behavior and generating a section with title of level X-1 (`"=" * X`). If that's not the intended behavior, feel free to close the issue.

Do note that closing this issue will still keep us with the behavior of a roundtrip: `adoc --[asciidoctor]--> html --[coradoc]--> adoc` that makes the clauses go up one level.
